### ISSUE TITLE
vNext multi-database connection string management/distribution

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#113]
Task force: @mauroservienti @justabitofcode 
Related to: https://github.com/Particular/PlatformDevelopment/issues/486
Related to: https://github.com/Particular/NServiceBus.SqlServer/issues/100
Connects to #139

Actually V2 of the transport supports the ability to [inject logic](http://docs.particular.net/nservicebus/sqlserver/multiple-databases#other-endpoints-pull-mode) to define the broker topology.

A proposal could be:

* migrate the actual multi-database implementation
* make it async/await compatible
* write a thin layer to wrap `pull` and `push` modes providing an API similar to:

```
busConfiguration.UseTransport<SqlServerTransport>()
     .UseSmartMagicalTopologyBuilder( new SqlTopologyStore() );
```

or

```
busConfiguration.UseTransport<SqlServerTransport>()
     .UseSmartMagicalTopologyBuilder( new AppSettingsTopologyStore() );
```

(Obviously `UseSmartMagicalTopologyBuilder` is a fictions name that must be changed.)

Using the same approach we could allow the user to plugin `cache` providers, etc.

```
busConfiguration.UseTransport<SqlServerTransport>()
     .UseSmartMagicalTopologyBuilder( new SqlTopologyStore(), new RedisTopologyCache() );
```

In order to support ServiceControl we need to provide an extension to the ServiceControl configuration  so that the configured `SmartMagicalTopologyBuilder` can be plugged in.

Using exactly the same technique as above we could plugin logic to distribute `schema` information even if all the endpoints are running on a single broker.

/cc @tmasternak @weralabaj @bording

**Comment by mauroservienti** [comment]
Given that IMO the actual implementation that automagically picks connection strings from the `AppSettings` based on a convention is problematic I suggest to turn it off and require the user to explicitly state what the endpoint should do, using a config such as:

```
busConfiguration.UseTransport<SqlServerTransport>()
     .UseSmartMagicalTopologyBuilder( new AppSettingsTopologyStore() );
```

to enable the v2 behavior.

**Comment by weralabaj** [comment]
Clarified by @mauroservienti: the intent is to support the v2 configuration for multi-schema/multi-db.

**Comment by ramonsmits** [comment]
We have two translations/lookups:

- Endpoint to connection string
- Endpoint to catalog, schema and/or table name

In a connection string a catalog can be specified but the actual catalog used in queries can be a different one.

It could also be a different connection strings between different instances of the endpoint when dealing with things like high availability groups.

### Which physical info in the headers

When processing a subscription or the return address for ReplyTo then what information should be put in the headers?

- catalog
- schema
- table/queue

Either we put only logical information in the headers or also physical information.

When putting physical info into the headers then probably include all except the connection string which should be the *host*

`catalog.schema.queuetable@host`

This would indicate, if you send a message then write it to `catalog.schema.queuetable` and use connectionstring `host`.

We now do not need a translation form logical endpoint to physical catalog, schema and table names. We only need to lookup/translate which connection string to use as that *must* be different for each process due to authorization.


### Connection string configuration

#### Schema

We currently have the ability to specify a schema (`Queue Schema`) in the connection string which is a bit weird. I don't understand why this is part of the connection string itself. It could be a potential attribute but then maybe as:

```
<connectionStrings>
  <add name="MyConnectionString" 
       connectionString="Data Source=INSTANCE_NAME; Initial Catalog=some_database; Integrated Security=True" prefix="catalogname.schemaname"/>
</connectionStrings>
```

Here I included not only the schema but also the *catalog* and not put it in the connection string on purpose. This allows connection sharing between for example transport and persistence but also improved connection pooling for a single process but even better connection pooling across processes on a single machine if username/password are part of the connection strings.


#### Connection string per 'host' instead of queue

The following configuration example will allow for only having to configure two connection string that is used by 5 queues. 

```
<connectionStrings>
   <add name="NServiceBus/Transport"      connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=nservicebus;Integrated Security=True" />
   <add name="NServiceBus/Transport/host" connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=nservicebus;Integrated Security=True"/>
</connectionStrings>

<UnicastBusConfig>
  <MessageEndpointMappings>
    <add Assembly="assemblya" Endpoint="queue-a" />
    <add Assembly="assemblyb" Endpoint="queue-b" />
    <add Assembly="assemblyc" Endpoint="queue-c@host" />
    <add Assembly="assemblyd" Endpoint="queue-d@host" />
    <add Assembly="assemblye" Endpoint="queue-e@host" />
  </MessageEndpointMappings>
</UnicastBusConfig>
```

Benefits:

- Only have to change a single connection string if for example the server would change for that set of queues.
- When adding an endpoint on the same 'host' we do not have to add a new connection string.
- The amount of configuration on an endpoint and servicecontrol is much less
- Added a subscriber does not result in having to explicitly have to add a configuration string for that specific queue. Only need when it is located on a unknown 'host'/sqlserver/connectionstring.

**Comment by ramonsmits** [comment]
In a discussion with @tmasternak I had the idea to just use SQL formatted fully qualified table names in the configuration after @tmasternak mentioned that the configured addresses can be transport specific.

For completeness I also added error and audit queue configuration:

```
<connectionStrings>
   <add name="NServiceBus/Transport"                connectionString="Integrated Security=True;Data Source=localhost" />
   <add name="NServiceBus/Transport/ServerX"        connectionString="Integrated Security=True;Data Source=serverx" />
   <add name="NServiceBus/Transport/ServiceControl" connectionString="Integrated Security=True;Data Source=servicecontrol" />
</connectionStrings>

<UnicastBusConfig>
  <MessageEndpointMappings>
    <add Assembly="assemblya" Endpoint="[catalog-a].[schema-x].[queue-a]" />
    <add Assembly="assemblyb" Endpoint="[catalog-a].[schema-y].[queue-b]" />
    <add Assembly="assemblyb" Endpoint="[catalog-a].[schema-y].[queue-b]@ServerX" />
  </MessageEndpointMappings>
</UnicastBusConfig>

<AuditConfig QueueName="[audit]@ServiceControl" OverrideTimeToBeReceived="00:10:00"/>

<MessageForwardingInCaseOfFaultConfig ErrorQueue="[error]@ServiceControl"/>
```

Benefits:

- No transformation needed as the table names are real T-SQL formatted table names.
- The table names don't even need to have a catalog and or schema to be defined. Only a table queue name would be sufficient too. We don't care
- Fully qualified table name syntax is understood by all DBA's
- We only need a conversion from 'host/server' to connection string.
 - The default would do a connection string lookup, an alternative could even be a string format of `Integrated Security=True;Data Source={0}`

**Comment by ramonsmits** [comment]
Regarding high-availability and fail-over we should just rely on the behavior of the sql client where different options can be configured via the connectionstring.

**Comment by ramonsmits** [comment]
After a discussion with @mauroservienti I even think we could even drop multi instance/server support.

``` xml
<connectionStrings>
   <add name="NServiceBus/Transport" connectionString="Integrated Security=True;Data Source=localhost" />
</connectionStrings>

<UnicastBusConfig>
  <MessageEndpointMappings>
    <add Assembly="assemblya" Endpoint="[schema-x].[queue-a]" />
    <add Assembly="assemblyb" Endpoint="[catalog-a]..[queue-b]" />
    <add Assembly="assemblyb" Endpoint="[catalog-a].[schema-y].[queue-b]" />
  </MessageEndpointMappings>
</UnicastBusConfig>

<AuditConfig QueueName="[audit]" OverrideTimeToBeReceived="00:10:00"/>

<MessageForwardingInCaseOfFaultConfig ErrorQueue="[error]"/>
```

The above configuration supports multi schema, multi catalog but not multi instance. 

Also note that I deliberately removed the schema and replaced it with `..`. In my opinion configuring these names are the responsibility of the user. If the user wants to use multiple catalogs then it is their responsibility to include the catalog in each endpoint address.

Maybe this syntax can even be different with other database vendors like *PostgreSQL* or *Oracle*. By not being to strict in the syntax we would support any addressing provided by a vender.

The above allows for 

- Transactions across multiple catalogs on the same instance
- Transactions across multiple catalogs on the same instance in a high availability group in SQL 2016

**Comment by johnsimons** [comment]
I just want the task force to whatever you decide to implement please please, test with SC and make sure it works.
Also if you think there will be changes to the configuration of SC, please talk to @gbiellem about what implications those changes have on the installer experience for a user.

**Comment by tmasternak** [comment]
@mauroservienti can we close this one as we have #149 and #139? 
/cc: @ramonsmits

**Comment by mauroservienti** [comment]
yes
