### ISSUE TITLE
Verify that distributed transactions are working on .NET 7

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.SqlServer#1145]
.NET 7 has added support for distributed transactions when running on Windows.

We should enable our `TransactionScope` tests for .NET 7 / Windows to verify that everything is working correctly.

Once that is done, we should update our [transaction](https://docs.particular.net/transports/sql/transactions#transaction-scope) docs to reflect these changes.

**Comment by andreasohlund** [comment]
@bording https://github.com/Particular/NServiceBus.SqlServer/pull/1243 proves that they work, lets close this one?

**Comment by bording** [comment]
Might be a good idea to leave this open until documentation is changed? We could also update the docs to explain how it would be possible to use with the existing packages by adding `TransactionManager.ImplicitDistributedTransactions = true` in a project.

**Comment by andreasohlund** [comment]
Turns out that a[ bug that we found and MS fixed in the .netframework driver](https://github.com/dotnet/SqlClient/issues/1124) didn't get ported to the .net version of the driver and is now blocking us from supporting transaction scopes with DTC. Note that transaction scopes do work and its just when escalating to DTC the mentioned deadlock happens.

@danielmarbach has [submitted a PR to fix this](https://github.com/dotnet/SqlClient/pull/2161) and once merged and released we can proceed with this

**Comment by SimonCropp** [comment]
there is a preview nuget with @danielmarbach fix if u want to test it

**Comment by SimonCropp** [comment]
i tested in Nsb.Attachments and it worked

**Comment by bording** [comment]
DTC tests are passing in #1267
