### ISSUE TITLE
Allow connection string to be changed at runtime

### ISSUE THREAD

**Issue by jmezach** [Particular/NServiceBus.SqlServer#1315]
#### Is your improvement related to a problem? Please describe.
We have a requirement where we need to be able to update the connection string at runtime. Specifically we're using [Hashicorp Vault](https://www.hashicorp.com/products/vault) to automatically provision a username/password combination on the fly, but these credentials are short lived and therefore need to be periodically refreshed, resulting in a new connection string. This does not seem to be a supported scenario right now as you can only pass a single connection string to the transport during startup.

#### Describe the suggested solution
We can think of two ways to solve this, by either allowing SqlServerTransport to leverage `IConfiguration` and getting the connection string from there. With the hot reloading feature of `IConfiguration` this would just work.

Alternatively the existing connection factory feature of the `SqlServerTransport` could be used, but that unfortunately doesn't currently allow access to the dependency injection container, which makes it hard to wire things up.

**Comment by WilliamBZA** [comment]
As you said, it's possible to use `IConfiguration` to get access to the connection string within a SqlConnection factory:

```CSharp
static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureServices(services =>
        {
            services.AddSingleton<MyService>();
        })
        .UseNServiceBus(c =>
        {
            var endpointConfiguration = new EndpointConfiguration("Sample.Core");
            endpointConfiguration.UseSerialization<SystemJsonSerializer>();
            endpointConfiguration.EnableInstallers();

            var routing = endpointConfiguration.UseTransport(new SqlServerTransport(async a =>
            {
                var connection = new SqlConnection(c.Configuration["connectionstring"]);
                await connection.OpenAsync();

                return connection;
            }));

            return endpointConfiguration;
        })
        .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>());
```

Alternatively, it seems like it's possible to access the `IServiceCollection` by registering an instance of `IServiceProviderFactory` within the builder and passing that as a parameter to the `CreateHostBuilder` method so that it can be accessed as a closure. [Here's](https://queil.net/2022/06/get-iservicecollection-from-host-builder/) an example that I used to validate this.

**Comment by jmezach** [comment]
I just realised we could use the connection factory to read the connection string from `IConfiguration` after I posted this issue. I am wondering though how often that would be called. I would assume every time NServiceBus would need a connection, but once it has been established it won't be called again. Perhaps when the connection is forcibly closed.I guess we'll have to do some experimentation with that.

**Comment by WilliamBZA** [comment]
Sounds like you've managed to load the connection string from `IConfiguration` within the factory method.

Which leaves us with the feature request...

> Still would be nice if there was something built-in for this though. Back in the old .NET Framework days we could just pass the name of the connection string to the transport and it would read it from configuration itself. I'm sure the same could be done here.

Due to the different ways that connection strings are configured in different hosting models (e.g. appsettings vs envvars in containers) loading of the connection string is not something that we want to take ownership of. We'd rather leave the code as accepting a connection string and let the consumers load that connection string from whatever source makes the most sense for them.
