### ISSUE TITLE
Documentation for v3: Connection pool guidance

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#136]
Task force: @tmasternak @weralabaj @justabitofcode @mauroservienti

Related to #100

**Comment by weralabaj** [comment]
@mauroservienti Not sure exactly what wast that about? New doco page? Should be opened in doco then?

**Comment by mauroservienti** [comment]
I don't know what this is about, it was in the original list in #100 when we decided to split issues.

@tmasternak do you remember what is this?

**Comment by tmasternak** [comment]
This was connected to the fact that sql connection pool is potentially shared by SqlTransport and any other Ado.Net code which uses the same connection string. It might result in situation that user will run out of connections in the pool because of that.

That being said I tried to come up with some valuable doco around that but apart from saying: "If you experience exceptions when opening connection due to max pool size being reached, you need to make it bigger".

**Comment by tmasternak** [comment]
Actually we might put such note in the connection string configuration section.
