### ISSUE TITLE
Spike a shovel/federation like solution for multi-instance/broker

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#146]
Task force: 
Related to https://github.com/Particular/docs.particular.net/issues/1103

multi-instance support as it is now is causing more issues than benefits and is not supported by our tools (see https://github.com/Particular/ServiceControl/issues/609 and https://github.com/Particular/ServiceControl/issues/618) the goal of this spike is to outline viable solution to provide a RabbitMQ shovel/federation like solution to customers using the SQL transport.

**Comment by ramonsmits** [comment]
But multi database, multi schema is still supported?

**Comment by mauroservienti** [comment]
@ramonsmits Multi-schema is alive and kicking, [multi-database/instance has been dropped](https://github.com/Particular/NServiceBus.SqlServer/issues/139)

**Comment by SzymonPobiega** [comment]
I am contemplating doing it as a small side project on my own but not sure yet (as I am not sure if I can bound the scope properly)

**Comment by andreasohlund** [comment]
I thought about this yesterday since I gave (without thinking about it) a user the [advice ](https://groups.google.com/d/msg/particularsoftware/VgXe9wHM0o4/q78bJLnHAwAJ)to use multidb to get store and forward.

What I came up with:

1. create a new standalone "relay" process
2. Users configure it to/gets scripts that:
   * Generate views in the involved DB's that mimics the tables that the senders would target
3. The view mentioned just points to a single "outgoing messages table"
4. The process reads those messages in groups batches etc to optimize for throughput
5. The process constantly tries to deliver those message for X until it "DLQ's" them in the source DB
   - If DTC is available this will be atomic, if not we'll rely on the receivers deduping just like we do today

Benefits:

* Separated from the endpoint since they just do a local send
* Routing is not effected since the "DB" dimension is hidden 
* Can send in batches.
* Can tune retries should the network between source and target DB be flaky


Observation:

This is very similar to what our gateway is doing today

**Comment by SzymonPobiega** [comment]
@andreasohlund I am not sure if this is similar to gateway because it is transparent and the gateway is not (which is IMO a :heavy_plus_sign: )

We have considered such a approach with @tmasternak but we dropped it in the initial design phases of SQL transport V3 because it would be hard to implement message driven pub-sub: the subscribe message would be sent to the destination queue (which exists in a different database) but no view has been created (yet) because the shovel didn't know about the subscribe message coming.

Now if we implement the native pub/sub using a store in a shared database, the shovel can periodically query the subscription store and create the views when it detects a subscription.

**Comment by mauroservienti** [comment]
I [build it for V5.x](https://github.com/mauroservienti/NServiceBus.Connector) it supports pub/sub in a transparent manner, it is a set of hacks replacing internal behaviors to overcome some of the design limitations of V5, limitations intentionally put in place to prevent such a thing (and I agree).
Anyway the above sample is a generic solution, transport agnostic, I don't see why we cannot provide something that is explicitly designed for SQL that knows how to handle all the scenarios.

**Comment by SzymonPobiega** [comment]
@mauroservienti I think there are two levels at which we can tap such a thing. Ideally we would have a black box that just works without endpoints knowing about it. I believe this would be possible if we had native pub-sub. 

Otherwise we need to provide a plug-in for the endpoints that would add/replace behaviors to the subscribe and unsubscribe pipelines to notify the shovel about new subscriptions.

**Comment by mauroservienti** [comment]
Since this is backlogged and I have no capacity, right now, I'll remove myself from the task force.

**Comment by SzymonPobiega** [comment]
https://github.com/SzymonPobiega/NServiceBus.Bridge solves this problem.
