### ISSUE TITLE
Provide better load-balancing of messages for small, batched message receive pattern

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#174]
Goal of this issues is to provide mechanisms that will enable better message load-balancing in scale-out scenarios for patterns when groups of small number of messages are written to the input queue.

See #154 for more details and rationale.

## PoA

- [x] Add peek batch size to `master` and test it #710
- [x] Add peek batch size to `release-6.2` and test it #711 
- [ ] Upgrade guide https://github.com/Particular/docs.particular.net/pull/5097
- [ ] Documentation https://github.com/Particular/docs.particular.net/pull/5099
- [x] Add to story

**Comment by mauroservienti** [comment]
The message pump at startup determines the batch size by doing `Math.Min(100, 10 * MaxConcurrency)`, which means that by setting concurrency to 1 the peek batch size will be 10. It seems to me it's too limiting as it might be beneficial to let the endpoint process, e.g., 5 messages concurrently but this would cause the batch size to be 50 which might still be problematic in low throughput with high message processing cost scenarios.

One option here is to allow the configuration of the batch size. If it's not set, the above algorithm is fine; otherwise, the message pump will respect the configured setting.

**Comment by tmasternak** [comment]
@mauroservienti I like the idea of enabling batch size adjustments.

**Comment by WilliamBZA** [comment]
Will be released in 6.2.0
