### ISSUE TITLE
Re-consider separating legacy dispatch code

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#206]
When implementing https://github.com/Particular/NServiceBus.SqlServer/issues/181 we failed to take the legacy dispatcher into account. Should we try to find some other way to separate the legacy-compliance concern without having a separate class?

**Comment by tmasternak** [comment]
Let me give the arguments for having `Legacy` classes (not only Dispatcher) in the first place the have a proper context:
 * LegacyMultiInstanceMode is legacy :P and moving code responsible for implementing it should make it easy to remove them in v4 of SqlServer transport
 * The key distinction between any Legacy and NonLegacy counterpart classes, is that for Legacy-type logic, transport address may get mapped to a distinct, potentially new SqlConnection (different sql instance). This enables encapsulation of complexity when setting up transactions and/or connections for doing any sql level operations
 * Legacy mode supports only `TransactionScope` receive strategy and e.g. `LegacyDispatcher` could be simplified making such assumptions about that.

**Comment by tmasternak** [comment]
Having all above in mind my first observation would be that in current design we failed to identify parts that will change for the same reasons. In this particular case the way we dispatch messages both for `Legacy` and `NonLegacy` mode.
It might be so that we should use composition to extract the common (read: changing for the same reasons) parts.

**Comment by SzymonPobiega** [comment]
PR opened #209 . Closing.
