### ISSUE TITLE
Headers are stored in `varchar` column

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#340]
### Symptoms

Characters not supported by database's collation are converted into `?` when used in headers (either as header name or value) leading to potential information loss.

### Who's affected

All users of SQL Server transport

### Description

The headers are stored in `varchar` column making in impossible to use higher Unicode symbols in the header name or value

**Comment by SimonCropp** [comment]
also CorrelationId and ReplyToAddress are varchar

![image](https://cloud.githubusercontent.com/assets/122666/22410191/f625ebea-e6e8-11e6-8161-019a81fd3b5e.png)

**Comment by SimonCropp** [comment]
@Particular/sqlserver-transport-maintainers so just to be clear this is data loss ?

**Comment by tmasternak** [comment]
@Particular/sqlserver-transport-maintainers  do we know what is the current behavior when sending non-ascii, unicode characters in message headers? /cc: @SimonCropp

**Comment by SimonCropp** [comment]
input header 

`sendOptions.SetHeader("dsfsdಠ_ಠsds", "dsfsdಠ_ಠsds");`

output header

`{[dsfsd?_?sds, dsfsd?_?sds]}`

**Comment by tmasternak** [comment]
@SimonCropp thx for the sample. Looking at the other issues regarding Unicode characters support. I think we should validate the header values and throw. 

@Particular/sqlserver-transport-maintainers I think this deserves a patch.

**Comment by SimonCropp** [comment]
@tmasternak 

>  I think we should validate the header values and throw.

Be aware headers can be populated by user input or business areas. and so it would seem justified to support unicode in this case??

**Comment by tmasternak** [comment]
@SimonCropp I see your point. My reasoning was this: 
 1. Currently we do not support Unicode. This was implicit decision but I would not call it a bug. The bug for me is the fact that we do not validate user input accordingly. 
 2. I agree that supporting Unicode could be valuable but should be treated as a feature and not a bug fix.

**Comment by SimonCropp** [comment]
> Currently we do not support Unicode. This was implicit decision but I would not call it a bug

@tmasternak i missed where this was described as an explicit decision. given the headers is passed to the transport as a string (which can be unicide) from the core i dont understand how the decision was made?

Just to be clear i am happy with saying "we dont support unicode headers" but that should be a core decision.

**Comment by SimonCropp** [comment]
also given "sql transport doesnt support unicode headers" is not documented, not validated, and is currently message loss i struggle to understand how you would convince a consumer of it to believe it is a feature

**Comment by tmasternak** [comment]
> @tmasternak i missed where this was described as an explicit decision.

@SimonCropp I'm not sure I'm following. As I said it was **implicit** decision made when we have chosen to store headers in `VARCHAR` column. 
I also don't agree that the decision has to be made at in `Core`. There are already differences when it comes to headers between transports e.g. the allowed total size for all headers. So I can imagine SqlServer not supporting Unicode characters.

> also given "sql transport doesnt support unicode headers" is not documented, not validated, and is currently message loss i struggle to understand how you would convince a consumer of it to believe it is a feature

This is the bug that I was talking about. The feature of supporting Unicode in headers that I mentioned  should include all of those.

**Comment by SzymonPobiega** [comment]
I am with @tmasternak on this one. We don't promise to support all kinds of weird things in the headers so as long as we throw before sending, this should be fine. Then we might asses the consequences of supporting unicode in the headers.

**Comment by tmasternak** [comment]
I did some thinking on the best places to make this validation and in my opinion it should be somewhere in the `Core` (I don't know the best place). The reasoning is this:
 * At the transport level we cannot validate until messages get to `Dispatcher`
 * This is problematic for `Outbox` as messages already stored in `Outbox` record are by assumption good to be sent
 * This could lead to situation when processing would fail due to messages getting stuck in `Outbox` and the only resolution for the user would be to delete them by hand on the level of persister sotrage.
 * This could also lead to some anomalies with Isolated dispatchers causing ghost messages in the scenarios when we can avoid them. E.g. invalid message sent in transaction (get's buffered in the connector), isolated dispatch succeeds, the connector sent fails only after isolated dispatch has been done.
 
@Particular/nservicebus-maintainers I guess that the best place in `Core` would be "as close to user code" as we can.

Thoughts?

**Comment by SzymonPobiega** [comment]
@tmasternak a super-ugly fix would be a a behavior added by the SQL transport that validates the headers in the beginning of the pipeline.

**Comment by andreasohlund** [comment]
I think the core is the best place to validate this. The headers are mutable all the way down but it seems that we could draw the line somewhere around the [RoutingToDispatchConnector](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs)

If we validate there we can make sure that that no unicode headers gets sent. While that's fine as safety switch I think we need to add more specific checks as well to give the users better guidance:

* When they call SendOptions.SetHeader
* When they register sagas and message types
* etc

Sagas and messages is the tricky part (since that info is propagated into headers) since that essentially blocks users from using their domain language of choice in both sagas and messages? (seems like a no go?)

**Comment by timbussmann** [comment]
> a super-ugly fix would be a a behavior added by the SQL transport that validates the headers in the beginning of the pipeline.

doesn't sounds that ugly to me?

> SendOptions.SetHeader

that wouldn't deal with incoming headers using unicode chars?

**Comment by andreasohlund** [comment]
>that wouldn't deal with incoming headers using unicode chars?

Sorry I was a bit unclear. My point was that in addition to the low level catch all checks we should have other checks as well in the user facing api parts to be able to give them better guidance so I was just listing things that came to mind.

The more I think of this the more I wonder if core is the right place for the checks?

The overall idea seems to be that we should support unicode (since we want to enable users to name sagas and messages in their native language if they wish so) and I can't think of anything in the core (or at least in the long run since MSMQ is still in there atm) that wouldn't work with unicode so given that perhaps it needs to be up to each component to prevent unicode to be used in their specific case?

**Comment by SimonCropp** [comment]
I thought the decision was to support Unicode. So nothing should be put In the core to block it

**Comment by andreasohlund** [comment]
Yea, my bad
