### ISSUE TITLE
Purge expired messages at startup (and not periodically)

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#396]
### What is the problem?

Users who do not use Time-To-Be-Received (TTBR) with the SQL Server transport still run the expired message purge task that unnecessarily increases the load on the queue table.

### What to do about it?

Revert to the old behaviour where the message pump discards expired messages when they are received. Purge the expired messages at startup only to support endpoints that cannot start because of high number of expired messages in the incoming queue table.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe how about we run that task only when we detect a TTBR message? Or at least 1 message per some time unit? This way users would not have another knob to thing about. Say if there is at least one expired TTBRed message per second detected, run the cleaner.

**Comment by MarcinHoppe** [comment]
Magic is nice but for troubleshooting, explicit control is nicer. This issue was created from a support case.

I will not object too much either way.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe we can have both. Magic will ensure it consumes less resources for the ignorant majority (people who don't care what TTBR even is) and the explicit "do not run cleanup" will comfort the ones that are aware of the trade offs.

**Comment by MarcinHoppe** [comment]
That I can live with 😄.

**Comment by SzymonPobiega** [comment]
Looking at the code in 3.x we don't receive the timed-out messages so we can't just disable the purge automatically because we would not get feedback if it is really needed.  I don't think it makes sense to have a sophisticated policy for how often to run the purge since it would be fragile.

Now that I think about it, what is the additional load if the expired message purge query finds no records to delete? Is it worth doing?

On the other hand, the 2.2.x version which is still used by SC has a number of flows that we did not address:
 * It uses unbounded deletes in the expired purge
 * The receive overlaps with the expired purge because it does not exclude the expired messages
 * The purge uses `UPDLOCK` instead of `NOLOCK`.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe ping?

**Comment by MarcinHoppe** [comment]
@SzymonPobiega How about:

```csharp
var transport = endpointConfiguration.UseTransport<SqlServer>();
transport.DoNotPurgeExpiredMessages();
```

?

**Comment by SzymonPobiega** [comment]
Ok, I was mistaken twice actually and the original thing I wrote is true:

> Looking at the code in 3.x we don't receive the timed-out messages so we can't just disable the purge automatically because we would not get feedback if it is really needed.  I don't think it makes sense to have a sophisticated policy for how often to run the purge since it would be fragile.

Now the question is what do we do:
 * Proceed with adding `DoNotPurgeExpiredMessages` risking that timed out messages will never be removed from the queue. 
 * Change the receive SQL to include the timed out messages (remove the `WHERE`). Add `DoNotPurgeExpiredMessages` or even add `PurgeExpiredMessages` and do not purge by default.

I don't like the first option because it carries a high risk of uncontrolled queue growth as the TTBR is controlled by the senders while purging -- by the receiver -> they can easily get out of sync.

**Comment by MarcinHoppe** [comment]
Let's revert to discard-upon-receive behaviour and only purge at startup.

@Particular/sqlserver-transport-maintainers I updated the title and description to reflect the new design.

**Comment by SzymonPobiega** [comment]
Created a PR to fix this here https://github.com/Particular/NServiceBus.SqlServer/pull/406

**Comment by MarcinHoppe** [comment]
The doco PR: https://github.com/Particular/docs.particular.net/pull/3366.

**Comment by MarcinHoppe** [comment]
Both the code and doco PRs have been merged. Closing.
