### ISSUE TITLE
Option  to use fully qualified table names to support multi-catalog usage on a single connection

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#454]
Currently queries executed include only the schema and table, but not the catalog. It assumes that the current connection is configured to have the correct database selected.

In a multi catalog setup this can cause issues if the catalog was changed, as the code that had set the catalog also needs to make sure that it resets the catalog to its previous value. This is also not possible in all scenarios.

Provide an option that allows to include the catalog in the queries so that you get `catalog.schema.tablename` which is known as fully qualified table names.

For example, this is very useful when having outbox enabled, where outbox data is stored in catalog X, but the customer modifies data via Entity Framework in catalog Y.  As is can now easily just call `SqlConnection.ChangeDatabase`. This is currently not easy to do and only possible as shown in the following gist:

https://gist.github.com/ramonsmits/8e63002f8caa6dc4fda61f9397035b44

**Comment by SzymonPobiega** [comment]
@ramonsmits that's not true since SQL supports multi-catalog (3.1 I believe). The `TableBasedQueue` uses the qualifiedTableName in the queries: https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs#L97. That qualified name comes from the `CanonicalQueueAddress` class and includes the catalog: https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Addressing/CanonicalQueueAddress.cs#L16

**Comment by SzymonPobiega** [comment]
@DorianGreen yes, the default one is read from the connection string. That's intentional.
