### ISSUE TITLE
Switch to `Particular.Approvals`

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#459]
## Overview
We should switch to `Particular.Approvals` instead of `ApprovalTests` otherwise we need to lock to 3.0.13 version to make the test run on .net core. See #458

**Comment by dbelcham** [comment]
Seems like this has been fixed in https://github.com/Particular/PlatformDevelopment/issues/2506 which has put the following PRs forward.
https://github.com/Particular/NServiceBus.SqlServer/pull/469
https://github.com/Particular/NServiceBus.SqlServer/pull/473
https://github.com/Particular/NServiceBus.SqlServer/pull/471
https://github.com/Particular/NServiceBus.SqlServer/pull/474

I'm going to close this. Re-open it if there is reason to.
