### ISSUE TITLE
Competing-consumer deployments might result in wasted `Select` queries

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#863]
Connected to: https://discuss.particular.net/t/performance-issues-on-upgrade-of-nservicebus-transport-sqlserver-from-6-0-1-to-6-2-0/2451/5

When multiple physical endpoints query the length of the input queue at the same time and the input queue size is less than peeking batch size (100 messages) majority of the `Select` statements for message receive will return empty results.

E.g. if there are 3 receiving endpoints and the are 50 messages in the input queue the following scenario can happen:
 * All 3 instances query the size and get 50 as a result
 * All 3 instances generate 50 `Select` statements to receive individual messages
 * 100 of the `Select` statements will result in empty results.

**Comment by MarcWils** [comment]
Hi @tmasternak, could newer versions still be affected by this issue?

I'm looking at an issue, which occurred multiple times on production, where we suddenly see **a lot** of dequeue SQL queries. The number of queries seem unrelated to the number of messages in the input queue. The high number of "bogus" dequeue queries cause a performance degredation in the SQL database. Derived based on the metrics the application is very busy dequeueing messages, but is not really processing a lot of messages.

We're using NServiceBus.Transport.SqlServer v6.3.4. If I understand the code correctly, the for-loop over the messageCount should break as soon a no message found anymore. 

https://github.com/Particular/NServiceBus.SqlServer/blob/35f177ca4120dec71e40254b514342fce6752d5b/src/NServiceBus.Transport.SqlServer/Receiving/MessagePump.cs#L144-L147

So this issue is no longer relevant?

I have also seen this issue (#1026).  Although it would be good if this would be fixed at some point, doesn't the same apply here? If no more message is found, the for-loop is stopped.

I'm just trying to understand what is happening to figger out our issue.

**Comment by SzymonPobiega** [comment]
Hi @MarcWils 

Yes, you are right, the peek loop should be stopped as soon as the first receive returns nothing. We would like to ask you some more questions regarding your environment. Would you mind opening a support case so that we can have a private conversation? Please mention there @tmasternak and/or myself to ensure the case gets routed to one of us.

**Comment by dvdstelt** [comment]
This problem has been fixed. You can find more information with these links:

- https://discuss.particular.net/t/nservicebus-sqlserver-7-0-5-and-6-3-7-patch-releases-available/3843
- https://github.com/Particular/NServiceBus.SqlServer/issues/1293
